# Generated by Django 4.1.2 on 2022-10-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.TextField(max_length=20),
        ),
    ]
